#!/bin/bash

NEWCRON=`md5sum /etc/crontab | cut -d " " -f1`

if [ -e "$HOME/.md5cron" ]
then
	read -r line < $HOME/.md5cron
	if [ "$line" != "$NEWCRON" ]
	then
		echo "Bonjour,\nLe fichier /etc/crontab a ete change !" | mail -s "Changement de /etc/crontab" root
		md5sum /etc/crontab | cut -d " " -f1 > $HOME/.md5cron
	fi
else
	ls ~
	touch $HOME/.md5cron
	md5sum /etc/crontab | cut -d " " -f1 > $HOME/.md5cron
fi
